-- (i) A Procedure called PROC_LAB5
DELIMITER

/

/

CREATE PROCEDURE PROC_LAB5(
    IN STARTDATE DATE,
    IN ENDDATE DATE
)
BEGIN
    SELECT
        ORDERS.ORDERID,
        CUSTOMERS.CUSTOMERNAME,
        CUSTOMERS.EMAIL,
        ORDERS.ORDERDATE,
        ORDERS.TOTALAMOUNT
    FROM
        ORDERS
        INNER JOIN CUSTOMERS
        ON ORDERS.CUSTOMERID = CUSTOMERS.CUSTOMERID
    WHERE
        ORDERS.ORDERDATE BETWEEN STARTDATE AND ENDDATE
    ORDER BY
        ORDERS.ORDERDATE;
END // DELIMITER;
 

-- (ii) A Function called FUNC_LAB5
DELIMITER // CREATE FUNCTION FUNC_LAB5(CUSTOMERID INT) RETURNS DECIMAL(10, 2) DETERMINISTIC
BEGIN
    DECLARE TOTALREVENUE DECIMAL(10, 2);
    SELECT
        SUM(ORDERS.TOTALAMOUNT) INTO TOTALREVENUE
    FROM
        ORDERS
    WHERE
        ORDERS.CUSTOMERID = CUSTOMERID;
    RETURN IFNULL(TOTALREVENUE, 0);
END // DELIMITER;
 
-- (iii) A View called VIEW_LAB5
CREATE VIEW VIEW_LAB5 AS
    SELECT ORDERS.ORDERID, CUSTOMERS.CUSTOMERNAME, COUNT(ORDERITEMS.ORDERITEMID) AS TOTALITEMS, ORDERS.TOTALAMOUNT FROM ORDERS INNER JOIN CUSTOMERS ON ORDERS.CUSTOMERID = CUSTOMERS.CUSTOMERID LEFT JOIN ORDERITEMS ON ORDERS.ORDERID = ORDERITEMS.ORDERID GROUP BY ORDERS.ORDERID, CUSTOMERS.CUSTOMERNAME, ORDERS.TOTALAMOUNT ORDER BY ORDERS.ORDERID;